name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run check-types

      - name: Lint and format
        run: bun run check

      - name: Build packages
        run: bun run build

      - name: Run backend tests
        run: bun run test --filter=server

      - name: Run frontend tests
        run: bun run test:run --filter=client

      - name: Install Playwright browsers
        run: bun --cwd apps/client playwright install chromium

      - name: Run E2E tests
        run: bun run test:e2e --filter=client
        env:
          CI: true
